name: Build iOS
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6 

      - name: Setup Node.js
        uses: actions/setup-node@v6 
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build -- --configuration=production

      - name: Capacitor Sync
        run: npx cap sync ios

      # This step packages the iOS folder so you can download it
      - name: Archive iOS Project
        run: zip -r ios-project.zip ios/App

      - name: Upload iOS Project Artifact
        uses: actions/upload-artifact@v6
        with:
          name: capacitor-ios-project
          path: ios-project.zip
          retention-days: 5
